blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_index'),
    path('post/list/', PostListView.as_view(), name='post_list'),
    path('post/detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),

    path('comment/create/<int:post_pk>/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/update/<int:post_pk>/<int:pk>', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/delete/<int:post_pk>/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
]

prography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('blog:post_list'), name='root'),
]

blog/models.py
from django.db import models
from django.shortcuts import reverse

class Post(models.Model):
    author = models.CharField(max_length=30)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}: {}'.format(self.author, self.title)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})
    


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return '{}: {}'.format(self.author, self.content)
    

blog/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['author', 'title', 'content']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'content']

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, resolve_url
from django.urls import reverse_lazy
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.views.generic import *


class PostListView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 3

    ordering = ['-created_at']

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = self.model.objects.filter(title__icontains=query).order_by('-created_at')
            paginator = Paginator(object_list, 3)
            page = self.request.GET.get('page')

            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                posts = paginator.page(1)
            except EmptyPage:
                posts = paginator.page(paginator.num_pages)
        else:
            object_list = self.model.objects.order_by('-created_at')
        return object_list

class PostCreateView(CreateView):
    model = Post
    fields = ['author', 'title', 'content']


class PostDetailView(DetailView):
    model = Post


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_index')


class CommentCreateView(CreateView):
    model = Comment
    fields = ['author', 'content']

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=self.kwargs['post_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url(self.object.post)


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ['content']

    def get_success_url(self):
        return resolve_url(self.object.post)


class CommentDeleteView(DeleteView):
    model = Comment
    
    def get_success_url(self):
        return resolve_url(self.object.post)

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-danger">
                <strong>주의! </strong> &nbsp; 한번 삭제하면 복구할 수 없습니다. 그래도 삭제하시겠습니까?
                <br><br>삭제를 원하시면 아래 '삭제하기' 버튼을 클릭하세요.
                </div>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="삭제하기">
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/comment_form.html
{% extends "blog/layout.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load static %}

{% block extra_head %}
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-danger">
                <strong>주의! </strong> &nbsp; 한번 삭제하면 복구할 수 없습니다. 그래도 삭제하시겠습니까?
                <br><br>삭제를 원하시면 아래 '삭제하기' 버튼을 클릭하세요.
                </div>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="삭제하기">
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered">
                <tr>
                    <td scope="col" style="width: 8.33%">
                        <strong>제목</strong>
                    </td>
                    <td>
                        {{ post.title }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>내용</strong>
                    </td>
                    <td>
                        {{ post.content|linebreaks }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>작성자</strong>
                    </td>
                    <td>
                        {{ post.author }}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="pull-right">
                <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">삭제</a>
                <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-primary">수정</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            &nbsp;
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <h4>{{ post.comment_set.all.count }}개의 댓글 목록</h3>
            <ul class="list-group">
                {% for comment in post.comment_set.all %}
                    <li class="list-group-item list-group-item-info">
                        {{ comment.author }}님
                    </li>
                    <li class="list-group-item">
                        {{ comment.content }}
                        <p class="text-right">&nbsp; <a href="{% url 'blog:comment_delete' post.pk comment.pk %}" class="btn btn-danger">삭제</a> <a href="{% url 'blog:comment_update' post.pk comment.pk %}" class="btn btn-info">수정</a></p>
                    </li>
                {% endfor %}
                <a href="{% url 'blog:comment_create' post.pk %}" class="btn btn-primary btn-block">
                    새 댓글 작성하기
                </a>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <a href="{% url 'blog:post_list' %}" class="btn btn-success btn-block">
                목록으로 이동
            </a>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="width: 8.33%">#</th>
                        <th scope="col">글 제목</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in post_list %}
                        <tr>
                            <th scope="row">
                                {{ post.id }}
                            </th>
                            <td>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-12">
            <a href="{% url 'blog:post_create' %}" class="btn btn-primary pull-right">새 글쓰기</a>
        </div>

        <nav aria-label="Page navigation example">
            <center>
                {% if is_paginated %}
                    <ul class="pagination justify-content-center">
                        {% if page_obj %}
                            {% if page_obj.has_previous %}
                                <li>
                                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">이전</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="#" style="background-color:rgba(18, 31, 18, 0.774);">이전</a>
                                </li>
                            {% endif %}
                            
                            {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}

                            
                            {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-default">다음</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="#" style="background-color:rgba(18, 31, 18, 0.774);">다음</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    </ul>
                {% endif %}
            </center>
        </nav>

        <div>
            <form>
                <div class="input-group">
                    <input name='q' type="text" class="form-control" placeholder="검색어를 입력하세요.">
                    <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

prography/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>prography blog</title>
        <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" crossorigin="anonymous">
        {% block extra_head %}{% endblock %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:post_index' %}">jcjang</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'blog:post_index' %}">Blog</a></li>
            </ul>
          </div>
        </div>
      </nav>

        {% block content %}
        {% endblock %}
        
        <div class="container">
            <hr>
            <footer>
              <p>2019 &copy; <a href="https://github.com/jangjichang" target="_blank">jcjang</a></p>
            </footer>
        </div>

        <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
    </body>
</html>